name: 1-building-block
'on': workflow_dispatch
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: 'echo "Hello, World"'
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Passed steps
        run: |
          exit 0
      - name: Say goodbye
        run: echo "GoodBye"
