name: 04-Using-Actions

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v5
        with:
              node-version: '24.x'
      - name: running tests
        run: npm run test
        working-directory: 04-using-actions/react-app