name: 06 - "Contexts"
run-name: 06-Contexts | DEBUG ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MY_ENV_VARIABLE: "env-variable"
  MY_OVERWRITTEN_VARIABLE: "over_env_variable"

jobs:
  echo-data:
    runs-on: ubuntu-latest

    env:
      MY_JOB_VARIABLE: "job-env-variable"
      MY_OVERWRITTEN_VARIABLE: "over_env_job_variable"

    steps:
      - name: Display Data
        run: |
          echo "Event_Name - ${{ github.event_name }}"
          echo "Ref - ${{ github.ref }}"
          echo "SHA - ${{ github.sha }}"
          echo "Actor - ${{ github.actor }}"
          echo "Workflow - ${{ github.workflow }}"
          echo "Run ID - ${{ github.run_id }}"
          echo "Run number - ${{ github.run_number }}"

      - name: Retrieve Variable
        run: |
          echo "Variable value - ${{ vars.MY_VARIABLE }}"

      - name: Print
        env:
          MY_OVERWRITTEN_VARIABLE: "over_env_step_variable"
        run: |
          echo "Env variable value - ${{env.MY_ENV_VARIABLE}}"
          echo "Job variable value - ${{env.MY_JOB_VARIABLE}}"
          echo "Overwritten variable value - ${{env.MY_OVERWRITTEN_VARIABLE}}"
      - name: Print
        run: |
          echo "Env variable value - ${{env.MY_ENV_VARIABLE}}"
          echo "Overwritten variable value - ${{env.MY_OVERWRITTEN_VARIABLE}}"
    
    echo-data:
      runs-on: ubuntu-latest
        run: |
          echo "Env variable value - $MY_ENV_VARIABLE"
          echo "Overwritten variable value - $MY_OVERWRITTEN_VARIABLE"
