name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step
      node-version:
        type: choice
        options:
          - 20.x
          - 21.x
          - 24.x
        default: 24.x

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 13-caching/react-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache node_modules
        if: ${{ inputs.use-cache }}
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('13-caching/react-app/package-lock.json') }}

      - name: Debug cache
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploying to non-prod
        run: echo "Deploying to nonprod"