name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 13-caching/react-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug files
        run: ls -la

      - name: Install dependencies
        run: npm install   # safer unless lock file exists

      - name: Test 
        run: npm run test

      - name: Build
        run: npm run build

      - name: Deploying to non-prod 
        run: echo "Deploying to nonprod"