Run ./.github/actions/js-dependency-update
/home/runner/work/CodeSpace-Example/CodeSpace-Example/.github/actions/js-dependency-update/node_modules/@actions/core/lib/core.js:106
        throw new Error(`Input required and not supplied: ${name}`);
              ^

Error: Input required and not supplied: gh-token
    at Object.getInput (/home/runner/work/CodeSpace-Example/CodeSpace-Example/.github/actions/js-dependency-update/node_modules/@actions/core/lib/core.js:106:15)
    at run (/home/runner/work/CodeSpace-Example/CodeSpace-Example/.github/actions/js-dependency-update/index.js:13:24)
    at Object.<anonymous> (/home/runner/work/CodeSpace-Example/CodeSpace-Example/.github/actions/js-dependency-update/index.js:98:1)
    at Module._compile (node:internal/modules/cjs/loader:1812:14)
    at Object..js (node:internal/modules/cjs/loader:1943:10)
    at Module.load (node:internal/modules/cjs/loader:1533:32)
    at Module._load (node:internal/modules/cjs/loader:1335:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47