name: 17 - 3 - Custom Actions - docker
run-name: 17 - 3 - Custom Actions - docker 
on:
  workflow_dispatch:
    inputs: 
      url:
        type: choice
        options:
          - 'https://www.google.com'
          - 'https://ggg'
      max-trials:
        description: "Maximum trials until action fails"
        type: number
        default: 10
      delay-seconds:
        description: "Delay in seconds between each trial"
        type: number
        default: 5
permissions:
  contents: write
  pull-requests: write

jobs: 
  ping-url:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: Docker - Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max-trials: ${{ inputs.max-trials }}
          delay-seconds: ${{ inputs.delay-seconds }}
      - name: Print URL Reachability
        run: echo "URL Reachable: ${{ steps.ping-url.outputs.url-reachable }}"